[package]
name = "nouveau"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "debuginfo"

[lib]
name = "nouveau_lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
itertools = "0.10.3"

[dev-dependencies]
test-case = "2.0.2"
insta = "1.13.0"
